# -*- coding: utf-8 -*-
"""Chapter 1, In_class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tbBCeMRfB-Un0dxKxUNVnMiN1u9YRVDZ
"""

##1

def recursive_sum(n):
    if n == 0:
        return 0

    return n + recursive_sum(n - 1)


print(recursive_sum(5))

##2

def recursive_length(text):
    if text == "":
        return 0

    return 1 + recursive_length(text[1:])


print(recursive_length("hello"))

##3

def reverse_string(text):
    if text == "":
        return ""

    return reverse_string(text[1:]) + text[0]


print(reverse_string("DATA"))

##4

# Recursive version
def fibonacci_recursive(n):
    if n <= 1:
        return n

    return fibonacci_recursive(n - 1) + fibonacci_recursive(n - 2)


# Iterative version
def fibonacci_iterative(n):
    if n <= 1:
        return n

    a, b = 0, 1

    for _ in range(2, n + 1):
        a, b = b, a + b

    return b


print(fibonacci_recursive(10))
print(fibonacci_iterative(10))

##5

def hanoi(n, source, auxiliary, target):
    if n == 1:
        print(f"Move disk 1 from {source} to {target}")
        return

    hanoi(n - 1, source, target, auxiliary)
    print(f"Move disk {n} from {source} to {target}")
    hanoi(n - 1, auxiliary, source, target)


hanoi(4, "A", "B", "C")

##6

def all_subsets(items):
    if not items:
        return [[]]

    rest = all_subsets(items[1:])

    return rest + [[items[0]] + subset for subset in rest]


subsets = all_subsets([1, 2, 3, 4])

print(subsets)
print(len(subsets))